### PR TITLE
Kill warning on sc misc driver

### PR DESCRIPTION
**Pull request by sasataku**
This PR reverts the following commit, which was added to kill the warning below,
and re-implements the warning suppression using the appropriate method.

 - revert commit
  * 9658d19d　drivers/misc: Remove zephyr_library()

- warnings
   ```
    CMake Warning at ...
       No SOURCES given to Zephyr library: ..__scsat1-fsw__drivers__misc
   ```

### CODE REVIEW

**Comment by yashi** [comment]
How can I enalbe `CONFIG_SC_DSTRX3` in menuconfig?

**Review by yashi — COMMENTED** [review]
How can I enalbe `CONFIG_SC_DSTRX3` in menuconfig?

**Comment by sasataku** [comment]
> How can I enalbe `CONFIG_SC_DSTRX3` in menuconfig?

You can reach it via the following path on MAIN board.
(Top) → Zephyr → Modules → scsat1-fsw (/home/sasataku/scsat1/scsat1-fsw) → Space Cubics Miscellaneous Drivers

However, `CONFIG_SC_DSTRX3` depends on `DT_HAS_SC_DSTRX3_ENABLED`, so if it is defined in the dts,it will be enabled by default.
On the ADCS board, since it is not defined in the DTS, it cannot be enabled.

**Comment by yashi** [comment]
I'm lost.

Does any of the boards including testing ones uses this driver at all?

**Comment by yashi** [comment]
Ah, Ok.  I was misunderstanding your comment.  Found it thanks.

**Review by yashi — APPROVED** [review]
LGTM.

**Pull request merged**
